import mongoose from 'mongoose';
const { Schema, model } = mongoose;

const campaignSchema = new Schema({
  name: {
    type: String,
    required: true,
    trim: true,
    minLength: 1,
  },

  owner: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },

  players: [{ type: Schema.Types.ObjectId, ref: 'User' }],
  characters: [{ type: Schema.Types.ObjectId, ref: 'Character' }],
  encounters: [{ type: Schema.Types.ObjectId, ref: 'Encounter' }],
  autogenerated: { type: Boolean, default: false },
});

const Campaign = model('Campaign', campaignSchema);

export default Campaign;
